version: '3'
services:
  folder-creator:
    build: .
    container_name: folder_creator
    ports:
      - "5050:5000"
    volumes:
      # Mapping /volume1 on NAS to /data in container
      - /volume1:/data
      - ./config:/config
    restart: unless-stopped
